## 计算设备

PyTorch可以指定⽤来存储和计算的设备，如使⽤内存的CPU或者使⽤显存的GPU。默认情况下，
PyTorch会将数据创建在内存，然后利⽤CPU来计算。

In [2]:
import torch
from torch import nn

torch.cuda.is_available()

True

In [3]:
torch.cuda.device_count()

1

In [4]:
torch.cuda.current_device()

0

In [5]:
torch.cuda.get_device_name(0)

'GeForce 940MX'

## TENSOR的GPU计算

In [6]:
x=torch.tensor([1,2,3])
x

tensor([1, 2, 3])

使⽤ .cuda() 可以将CPU上的 Tensor 转换（复制）到GPU上。如果有多块GPU，我们⽤ .cuda(i)
来表示第 块GPU及相应的显存（ 从0开始）且 cuda(0) 和 cuda() 等价。

In [7]:
x=x.cuda(0)
x

tensor([1, 2, 3], device='cuda:0')

我们可以通过 Tensor 的 device 属性来查看该 Tensor 所在的设备。

In [8]:
x.device

device(type='cuda', index=0)

In [11]:
device=torch.device('cuda' if torch.cuda.is_available() else 'cpu')
x=torch.tensor([1,2,3],device=device) #or
x=torch.tensor([1,2,3]).to(device)
x

tensor([1, 2, 3], device='cuda:0')

In [12]:
y=x*2
y

tensor([2, 4, 6], device='cuda:0')

In [13]:
z=y+x.cpu()

RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!

## 模型的GPU计算

In [14]:
net=nn.Linear(3,1)
list(net.parameters())[0].device

device(type='cpu')

In [15]:
net.cuda()
list(net.parameters())[0].device

device(type='cuda', index=0)

In [16]:
x=torch.rand(2,3).cuda()
net(x)

tensor([[-0.2230],
        [-0.5549]], device='cuda:0', grad_fn=<AddmmBackward>)