In [1]:
import torch

### 创建Tensor

In [2]:
#创建一个5*3的未初始化的Tensor
x=torch.empty(5,3)
print(x)

tensor([[8.9082e-39, 9.8265e-39, 9.4592e-39],
        [1.0561e-38, 1.0653e-38, 1.0469e-38],
        [9.5510e-39, 1.0378e-38, 8.9082e-39],
        [9.6429e-39, 8.9082e-39, 9.1837e-39],
        [1.0010e-38, 1.0286e-38, 1.6956e-43]])


In [3]:
#创建一个5*3的随机初始化的Tensor
x=torch.rand(5,3)
print(x)

tensor([[0.9088, 0.1529, 0.2951],
        [0.9579, 0.1178, 0.8992],
        [0.6120, 0.4657, 0.9614],
        [0.5849, 0.8409, 0.9280],
        [0.7214, 0.4049, 0.8886]])


In [4]:
#创建一个5*3的long型全0的Tensor
x=torch.zeros(5,3,dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [5]:
#根据数据创建
x=torch.tensor([5.5,3])
print(x)

tensor([5.5000, 3.0000])


In [8]:
#根据现有Tensor创建
x=x.new_ones(5,3,dtype=torch.float64)
print(x)
x=torch.randn_like(x,dtype=torch.float)#指定新的数据类型
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[-0.6400,  1.1500, -0.6813],
        [-1.8840, -0.4631, -0.5259],
        [-1.9029,  0.0992,  0.6612],
        [-0.2438, -1.1222,  0.3006],
        [-1.8822,  1.3868, -2.3430]])


In [9]:
#通过shape或者size()来获取Tensor的形状
print(x.size())
print(x.shape)

torch.Size([5, 3])
torch.Size([5, 3])


### 操作

算术操作

In [36]:
#加一
y=torch.rand(5,3)
print(x+y)

tensor([[-0.5871,  1.4559, -0.6118],
        [-1.5011,  0.1294, -0.3774],
        [-1.2871,  0.1029,  0.9082],
        [ 0.2695, -1.0141,  1.2886],
        [-1.6873,  1.9408, -1.3522]])


In [37]:
#加二
print(torch.add(x,y))

#还可以指定输出
result=torch.empty(5,3)
torch.add(x,y,out=result)
print(result)

tensor([[-0.5871,  1.4559, -0.6118],
        [-1.5011,  0.1294, -0.3774],
        [-1.2871,  0.1029,  0.9082],
        [ 0.2695, -1.0141,  1.2886],
        [-1.6873,  1.9408, -1.3522]])
tensor([[-0.5871,  1.4559, -0.6118],
        [-1.5011,  0.1294, -0.3774],
        [-1.2871,  0.1029,  0.9082],
        [ 0.2695, -1.0141,  1.2886],
        [-1.6873,  1.9408, -1.3522]])


In [38]:
#加三 inplace
#adds x to y
y.add_(x)
print(y)

tensor([[-0.5871,  1.4559, -0.6118],
        [-1.5011,  0.1294, -0.3774],
        [-1.2871,  0.1029,  0.9082],
        [ 0.2695, -1.0141,  1.2886],
        [-1.6873,  1.9408, -1.3522]])


索引  
    我们还可以使⽤类似NumPy的索引操作来访问 Tensor 的⼀部分，需要注意的是：索引出来的结果与原数据共享内存，也即修改⼀个，另⼀个会跟着修改。

In [41]:
y=x[0,:]
print(y)
y+=1
print(y)
print(x[0,:])

tensor([1.3600, 3.1500, 1.3187])
tensor([2.3600, 4.1500, 2.3187])
tensor([2.3600, 4.1500, 2.3187])


改变形状

In [49]:
y=x.view(15)
z=x.view(-1,5) #-1所指的维度可以根据其他维度的值推出来
print(x.size(),y.size(),z.size())
print(x)
print(y)
print(z)

torch.Size([5, 3]) torch.Size([15]) torch.Size([3, 5])
tensor([[ 3.3600,  5.1500,  3.3187],
        [-0.8840,  0.5369,  0.4741],
        [-0.9029,  1.0992,  1.6612],
        [ 0.7562, -0.1222,  1.3006],
        [-0.8822,  2.3868, -1.3430]])
tensor([ 3.3600,  5.1500,  3.3187, -0.8840,  0.5369,  0.4741, -0.9029,  1.0992,
         1.6612,  0.7562, -0.1222,  1.3006, -0.8822,  2.3868, -1.3430])
tensor([[ 3.3600,  5.1500,  3.3187, -0.8840,  0.5369],
        [ 0.4741, -0.9029,  1.0992,  1.6612,  0.7562],
        [-0.1222,  1.3006, -0.8822,  2.3868, -1.3430]])


In [50]:
#view()返回的新tensor与源tensor共享内存，即改变其中一个，另外一个也会跟着改变。
x+=1
print(x)
print(y)
print(z)

tensor([[ 4.3600,  6.1500,  4.3187],
        [ 0.1160,  1.5369,  1.4741],
        [ 0.0971,  2.0992,  2.6612],
        [ 1.7562,  0.8778,  2.3006],
        [ 0.1178,  3.3868, -0.3430]])
tensor([ 4.3600,  6.1500,  4.3187,  0.1160,  1.5369,  1.4741,  0.0971,  2.0992,
         2.6612,  1.7562,  0.8778,  2.3006,  0.1178,  3.3868, -0.3430])
tensor([[ 4.3600,  6.1500,  4.3187,  0.1160,  1.5369],
        [ 1.4741,  0.0971,  2.0992,  2.6612,  1.7562],
        [ 0.8778,  2.3006,  0.1178,  3.3868, -0.3430]])


In [51]:
#返回一个副本
x_cp=x.clone().view(15)
x-=1
print(x)
print(x_cp)

tensor([[ 3.3600,  5.1500,  3.3187],
        [-0.8840,  0.5369,  0.4741],
        [-0.9029,  1.0992,  1.6612],
        [ 0.7562, -0.1222,  1.3006],
        [-0.8822,  2.3868, -1.3430]])
tensor([ 4.3600,  6.1500,  4.3187,  0.1160,  1.5369,  1.4741,  0.0971,  2.0992,
         2.6612,  1.7562,  0.8778,  2.3006,  0.1178,  3.3868, -0.3430])


In [52]:
#item()函数，可以将标量tensor转换成一个python number
x=torch.randn(1)
print(x)
print(x.item())

tensor([0.0136])
0.013601233251392841


广播机制

运算的内存开销

TENSOR 和 NUMPY 相互转换

TENSOR ON GPU

### 自动求梯度

Tensor 是这个包的核⼼类，如果将其属性 .requires_grad 设置为 True ，它将开始追
踪(track)在其上的所有操作（这样就可以利⽤链式法则进⾏梯度传播了）。完成计算后，可以调
⽤ .backward() 来完成所有梯度计算。此 Tensor 的梯度将累积到 .grad 属性中

In [26]:
#创建一个Tensor并设置 requires_grad=true
x=torch.ones(2,2,requires_grad=True)
print(x)
print(x.grad_fn)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)
None


In [27]:
y=x+2
print(y)
print(y.grad_fn)

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)


In [28]:
#像x这种直接创建的称为叶⼦节点，叶⼦节点对应的 grad_fn 是 None 
print(x.is_leaf,y.is_leaf)

True False


In [29]:
z=y*y*3
out=z.mean()
print(z,out)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>) tensor(27., grad_fn=<MeanBackward0>)


In [30]:
#通过 .requires_grad_() 来⽤in-place的⽅式改变 requires_grad 属性：
a=torch.randn(2,2) # 缺失情况下默认 requires_grad = False
a=((a*3)/(a-1))
print(a.requires_grad)
a.requires_grad_(True)
print(a.requires_grad)
b=(a*a).sum()
print(b.grad_fn)

False
True


In [31]:
#因为 out 是⼀个标量，所以调⽤ backward() 时不需要指定求导变量：
out.backward()  # 等价于 out.backward(torch.tensor(1.))

In [32]:
print(x.grad)

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])


In [33]:
out2=x.sum()
out2.backward()
print(x.grad)

out3=x.sum()
x.grad.data.zero_()
out3.backward()
print(x.grad)

tensor([[5.5000, 5.5000],
        [5.5000, 5.5000]])
tensor([[1., 1.],
        [1., 1.]])


In [37]:
x=torch.tensor([1.0,2.0,3.0,4.0],requires_grad=True)
y=2*x
z=y.view(2,2)
print(z)

tensor([[2., 4.],
        [6., 8.]], grad_fn=<ViewBackward>)


In [38]:
#现在 y 不是⼀个标量，所以在调⽤ backward 时需要传⼊⼀个和 y 同形的权᯿向量进⾏加权求和得到⼀个标量。
v=torch.tensor([[1.0,1.0],[1.0,1.0]],dtype=torch.float)
z.backward(v)
print(x.grad)

tensor([2., 2., 2., 2.])


In [40]:
x=torch.tensor(1.0,requires_grad=True)
y1=x**2
with torch.no_grad():
    y2=x**3
y3=y1+y2
print(x.requires_grad)
print(y1,y1.requires_grad)
print(y2,y2.requires_grad)
print(y3,y3.requires_grad)
y3.backward()
print(x.grad)

True
tensor(1., grad_fn=<PowBackward0>) True
tensor(1.) False
tensor(2., grad_fn=<AddBackward0>) True
tensor(2.)


In [41]:
x=torch.ones(1,requires_grad=True)
print(x.data)
print(x.data.requires_grad)

y=2*x
x.data *=100
y.backward()
print(x)
print(x.grad)

tensor([1.])
False
tensor([100.], requires_grad=True)
tensor([2.])
