## 读写TENSOR

我们可以直接使⽤ save 函数和 load 函数分别存储和读取 Tensor 。 save 使⽤Python的pickle实⽤
程序将对象进⾏序列化，然后将序列化的对象保存到disk，使⽤ save 可以保存各种对象,包括模型、张
量和字典等。⽽ laod 使⽤pickle unpickle⼯具将pickle的对象⽂件反序列化为内存。

In [3]:
import torch
from torch import nn

x=torch.ones(3)
torch.save(x,'x.pt')

In [4]:
x2=torch.load('x.pt')
print(x2)

tensor([1., 1., 1.])


In [5]:
y=torch.zeros(4)
torch.save([x,y],'xy.pt')
xy_list=torch.load('xy.pt')
xy_list

[tensor([1., 1., 1.]), tensor([0., 0., 0., 0.])]

In [6]:
torch.save({'x':x,'y':y},'xy_dict.pt')
xy=torch.load('xy_dict.pt')
xy

{'x': tensor([1., 1., 1.]), 'y': tensor([0., 0., 0., 0.])}

## 读写模型

### state_dict

state_dict 是⼀个从参数名称隐射到参数 Tesnor 的字典对象

In [7]:
class MLP(nn.Module):
    def __init__(self):
        super(MLP,self).__init__()
        self.hidden=nn.Linear(3,2)
        self.act=nn.ReLU()
        self.output=nn.Linear(2,1)
    def forward(self,x):
        a=self.act(self.hidden(x))
        return self.output(a)
net=MLP()
net.state_dict()

OrderedDict([('hidden.weight',
              tensor([[-0.2831,  0.5174,  0.4192],
                      [-0.5686, -0.0802,  0.2640]])),
             ('hidden.bias', tensor([0.2388, 0.1167])),
             ('output.weight', tensor([[-0.1074,  0.2947]])),
             ('output.bias', tensor([0.1011]))])

In [8]:
optimizer=torch.optim.SGD(net.parameters(),lr=0.001,momentum=0.9)
optimizer.state_dict()

{'state': {},
 'param_groups': [{'lr': 0.001,
   'momentum': 0.9,
   'dampening': 0,
   'weight_decay': 0,
   'nesterov': False,
   'params': [0, 1, 2, 3]}]}

### 保存和加载模型

#### 保存和加载state_dict（推荐方式）

    torch.save(model.state_dict(),PATH)#推荐的文件后缀名是pt或pth

    model=TheModelClass(*args,**kwargs)
    model.load_state_dict(torch.load(PATH))

#### 保存和加载整个模型

    torch.save(model,PATH)

    model=torch.load(PATH)

In [10]:
X=torch.randn(2,3)
Y=net(X)

PATH='./net.pt'
torch.save(net.state_dict(),PATH)

net2=MLP()
net2.load_state_dict(torch.load(PATH))
Y2=net2(X)
Y2==Y

tensor([[True],
        [True]])